const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync('index.html','utf8').split('/* COPILOT_STATUS_SYNC_START */')[1].split('/* COPILOT_STATUS_SYNC_END */')[0];
const values={};const context={URL,Date,Number,JSON,COPILOT_CONFIRMED:{},JOB_STATES:{'https://jobs.example.com/manual':'saved'},JOB_STATE_KEY:'states',ALL_JOBS:[{url:'https://jobs.example.com/job/1/?utm_source=feed'}],jobId:j=>j.url,localStorage:{setItem:(k,v)=>values[k]=v}};vm.createContext(context);vm.runInContext(source,context);
assert.equal(context.importCopilotConfirmed([{url:'https://jobs.example.com/job/1',status:'applied'}]),0);
assert.equal(context.JOB_STATES[context.ALL_JOBS[0].url],undefined);
assert.equal(context.importCopilotConfirmed([{url:'https://jobs.example.com/job/1',status:'applied',job_id:'1234567890abcdef',submitted_at:'2026-10-09T00:00:00Z'}]),1);
assert.equal(context.JOB_STATES[context.ALL_JOBS[0].url],'applied');
assert.equal(context.JOB_STATES['https://jobs.example.com/manual'],'saved');
assert.equal(context.importCopilotConfirmed([{url:'javascript:alert(1)',status:'applied',job_id:'1234567890abcdef',submitted_at:'2026-10-09T00:00:00Z'}]),0);
assert.equal(context.importCopilotConfirmed([{url:'https://jobs.example.com/job/1',status:'applied',job_id:'1234567890abcdef',submitted_at:'2026-10-09T00:00:00Z'}]),0);
console.log('Receipt-backed status sync, URL aliases and preservation checks passed');
