Skip to content
kotnala-harshit
job-dashboard
Repository navigation
Code
Issues
Pull requests
Actions
Projects
Wiki
Security and quality
Insights
Settings
Scrape jobs
Scrape jobs #72
All jobs
Run details
Annotations
1 error and 1 warning
scrape
failed 18 minutes ago in 14m 32s
Search logs
1s
1s
0s
13m 38s
50s
Run git config user.name "job-dashboard-bot"
[main 82dd64a] Update job data 2026-08-07T23:48:40Z
 1 file changed, 11001 insertions(+), 2092 deletions(-)
error: cannot pull with rebase: You have unstaged changes.
error: Please commit or stash them.
Push attempt 1 failed, retrying in 10s...
error: cannot pull with rebase: You have unstaged changes.
error: Please commit or stash them.
Push attempt 2 failed, retrying in 10s...
error: cannot pull with rebase: You have unstaged changes.
error: Please commit or stash them.
Push attempt 3 failed, retrying in 10s...
error: cannot pull with rebase: You have unstaged changes.
error: Please commit or stash them.
Push attempt 4 failed, retrying in 10s...
error: cannot pull with rebase: You have unstaged changes.
error: Please commit or stash them.
Push attempt 5 failed, retrying in 10s...
All push attempts failed
Error: Process completed with exit code 1.
0s
0s
0s
